### ISSUE TITLE
RAVDESS is misspelled as RAVDEES everywhere in the repo

### ISSUE THREAD

**Issue by AnkushMalaker** [AnkushMalaker/speech-emotion-recognition#7]

**Comment by twelsh37** [comment]
Hey Ankush, Id like to take this issue as my  first ever contribution. do I just do a git pull  fix the issue and then push a merfe request?

**Comment by AnkushMalaker** [comment]
Hey, @twelsh37 . Glad to hear you're looking to start making contributions to open-source projects. You would need to fork the repository, make the changes, commit, and push the changes into your own repository. Then, you can open a pull request. If there are any further changes to be made, I'll let you know, if not, I'll merge it with this one.

**Comment by chirag0527** [comment]
Hi Ankush. I just created a PR for this issue. Since this was my first open source contribution, I am skeptical whether I did it right or if something went wrong. Can you please check and revert back?

**Comment by twelsh37** [comment]
> Hey, @twelsh37 . Glad to hear you're looking to start making contributions to open-source projects. You would need to fork the repository, make the changes, commit, and push the changes into your own repository. Then, you can open a pull request. If there are any further changes to be made, I'll let you know, if not, I'll merge it with this one.

Thankd for the heads up. I just ran through the first-contributor tutorial. Now I know what to do. Do you still need this of has Chirag0527 finished the job?

**Comment by AnkushMalaker** [comment]
Hey, @twelsh37 . It seems Chirag has done the job already. If you want, you can look at other issues in this repository and take one of those up. #4 and #5 should be quick and easy fixes for you to try. Thanks and best of luck.

**Comment by AnkushMalaker** [comment]
Thanks for the excellent first contribution, @chirag0527 .
Fixed with #8
